#!/bin/bash

DIR="$(dirname "${BASH_SOURCE[0]}")"

cd $DIR/..

# Create database folder
mkdir -p database/

OUT=hagrid/settings/flags/secret_key.py
if [ -f "$OUT" ]; then
    echo "Secret key already set!" 1>&2

    if [ "$1" != "--force" ]; then
        echo "Flag --force not provided; Aborting!" 1>&2
        exit 0
    else
        echo "Force overriding!"
        echo ""
    fi
fi

# SECRET_KEY randomly generated
echo "" > $OUT
echo "# ----------------------------" >> $OUT
echo "# Generated by gen_settings.sh" >> $OUT
echo "# ----------------------------" >> $OUT
echo "# SECURITY WARNING: keep the key used in production secret!" >> $OUT
echo "# Django configuration." >> $OUT
echo "#----------------------" >> $OUT
SECRET_KEY=$(./tools/secret_key.py)
echo "SECRET_KEY = '${SECRET_KEY}'" >> $OUT
echo "Default '$OUT' generated"
